AWSTemplateFormatVersion: 2010-09-09
Description: >-
  It creates a dynamodb table, ec2 instance with ssh access and policy that 
  let's the instance query the database
  
Parameters:
  InstanceType: 
    Description: Amazon EC2 instance type for the Virtual Machine
    Type: String
    AllowedValues:
      - t2.micro
  VpcId:
    Description: Existing default VPC in the Availability Zone.
    Type: AWS::EC2::VPC::Id
  KeyPairName:
    Description: Security Credentials used to connect to the EC2 instances via SSH.
    Type: AWS::EC2::KeyPair::KeyName
  ImageId:
    Type: String
    Default: ami-0de53d8956e8dcf80
    Description: ImageId for EC2 Instance

Resources:
  #dynamodb table
  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Product_table
      AttributeDefinitions:
        - AttributeName: "Make"
          AttributeType: "S"
        - AttributeName: "Model"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Make"
          KeyType: "HASH"
        - AttributeName: "Model"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1" 
  
  # iam role
  EC2DDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2DBRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'

  # iam policy
  EC2DDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: QueryAccesstoDynamoDB
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:*
            Resource: arn:aws:dynamodb:*:*:table/Product_table
      Roles: !Ref EC2DDBRole
  
  # instance profile
  EC2DDBInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: !Ref EC2DDBRole
      
  # ec2 instance
  EC2Instance:
    Type: AWS::EC2::Instance 
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref KeyPairName
      # ssh access
      SecurityGroupIds: 
        - !Ref SSHSecGroup
      # 
      IamInstanceProfile: !Ref EC2DDBInstanceProfile
  
  # web security group
  SSHSecGroup:
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupDescription: SSH Access for EC2 Instance.
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      # ssh rule
        -
          CidrIp: 0.0.0.0/0 
          IpProtocol: tcp
          FromPort: 22 
          ToPort: 22
  