AWSTemplateFormatVersion: 2010-09-09

Description: RDS stack

# parameters and constraints
Parameters:
  DBClass:
    Type: String
    Description: RDS Instance Class
    # allowed values parameter
    AllowedValues: 
      - db.t2.micro
      - db.t2.small
    ConstraintDescription: 'DBClass parameter can only have these values: db.t2.micro, db.t2.small'
    Default: db.t2.micro
  MasterUserName:
    Type: String
    Description: Master Username for the Database Instance
    MaxLength: 10
    Default: dbadmin
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: MasterUsername must begin with a letter and it cannot exceed 10 characters
    NoEcho: true
  MasterUserPassword:
    Type: String
    Description: Master User Passowrd for the Database Instance
    MinLength: 8
    NoEcho: true
  MultiAZ:
    Type: String
    Description: Enable Multi-AZ feature on the DB Instance 
    AllowedValues:
      - true
      - false
    ConstraintDescription: MultiAZ parameter should be either true or false
    Default: false
  AllocatedStorage:
    Type: Number
    Description: Database Storage Size in GB
    MinValue: 8
    MaxValue: 20
    # custom error message for number type constraint
    ConstraintDescription: AllocatedStorage parameter value should be between 8 and 20 GBs.
    # default value for parameter
    Default: 8
  SecurityGroupPorts:
    Type: List<Number>
    Description: 'Port number as a list <web-server-port>, <database-port>'

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-0c95efde864c744ca
      GroupDescription: 'Web Server instances security group'
      SecurityGroupIngress:
        - 
          CidrIp: 0.0.0.0/0
          # sec group ref for web is the first index on the list
          FromPort:
            Fn::Select: [ 0, !Ref SecurityGroupPorts ]
          ToPort: !Select  [ 0, !Ref SecurityGroupPorts ]
          IpProtocol: tcp
  # db security group
  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-0c95efde864c744ca
      GroupDescription: 'Database instances security group'
      SecurityGroupIngress:
        - 
          CidrIp: 0.0.0.0/0
          # sec group ref for db is the second index on the list
          FromPort: !Select [ 1, !Ref SecurityGroupPorts ]
          ToPort: !Select [ 1, !Ref SecurityGroupPorts ]
          IpProtocol: tcp
  # db subnet group - resource in which rds instances can be launched into
  DbSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnets to launch db instances into
      SubnetIds: 
        - subnet-0ee568d79403663d4
        - subnet-08559baafb9e926ad
        - subnet-0d5f182b8337b9d83
  # rds instance
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref DBClass
      Engine: mariadb
      MultiAZ: !Ref MultiAZ
      PubliclyAccessible: true
      AllocatedStorage: !Ref AllocatedStorage
      MasterUsername: !Ref MasterUserName
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups: 
        - !Ref DbSecurityGroup
      